   name: Jekyll site CI
   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-ruby@v3
         with:
           ruby-version: '3.1'
           bundler-cache: true
       - run: bundle exec jekyll build --destination ./_site
       - uses: actions/deploy-pages@v2
